---
author: "Mary Petersen"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## the purpose: rewriting reproducibly
The goal of this project is to take a formerly non-reproducible report and transform it into a reproducible formart. Reproducible reports focus on connecting the written report or paper directly to the analysis and data behind the findings. By doing this, the risks of copy-paste errors are avoided and organization improves as well. This system simplifies processes when working with collaborators and makes it significantly easier when looking through past work. Let this project serve as an example of the transformation of a traditional report into a reproducible report and highlight the key benefits towards report writing in a reproducible manner.

## the report: experimental determination of friction factor
The objective of this specific report is to determine the friction factor of a straight PVC pipe. An Armfield flow bench apparatus will be used, and the experimental friction values will be compared to the literature values in a Moody chart.

## the apparatus: armfield flow bench
The Armfield flow bench apparatus functions using an adjustible flow pump, cycling water from a reservoir though the straight pipe and back. The pump speed is adjusted to the desired flow rate. Three manometers are attached to the pipe spaced 20 centimeters apart to measure pressure; however only two will be used.